GET http://localhost:9000/api/data/category

###
GET http://localhost:9000/api/data/category?tag_id=1

###
GET http://localhost:9000/api/data

###
GET http://localhost:9000/api/data?tag_id=1

###
POST http://localhost:9001/api/data
Content-Type: application/json

{
    "categoryId": 1,
    "subCategoryId": 3,
    "tagId": 3,
    "amount": 100
}

###
PUT http://localhost:9001/api/data/5
Content-Type: application/json

{
    "amount": 30000
}

###
DELETE http://localhost:9000/api/data/1