GET http://localhost:9000/api/tag

###

POST http://localhost:9000/api/tag
Content-Type: application/json

{
    "name": "yuki"
}

###

PUT  http://localhost:9000/api/tag/1
Content-Type: application/json

{
    "name": "malney"
}

###

DELETE  http://localhost:9000/api/tag/1